#!/bin/sh

# fix permissions
chown -R root:root /opt/shieldtra/netdown
chown -R root:root /opt/shieldtra/shieldtraservice
chown -R root:root /opt/shieldtra/openvpn

if [ -x /bin/systemctl ]; then
    systemctl enable shieldtra
    systemctl start shieldtra
fi

#DEBHELPER#
exit 0
