#!/bin/sh

# fix permissions
chown -R root:root /opt/safejumper/launchopenvpn
chown -R root:root /opt/safejumper/netdown
chown -R root:root /opt/safejumper/safejumperservice
chown -R root:root /opt/safejumper/openvpn

if [ -x /bin/systemctl ]; then
    systemctl enable safejumper
    systemctl start safejumper
fi

#DEBHELPER#
exit 0
